### ISSUE TITLE
Hello from CCCS! 🍁

### ISSUE THREAD

**Issue by cccs-rs** [apophis133/apophis-YARA-Rules#1]
Hi there,

I was wondering if you're interested in including your extractors in [Assemblyline](https://cybercentrecanada.github.io/assemblyline4_docs/), our open-source malware analysis platform.

I believe adding the work that you've done would be a boon to the cybersecurity community!

If you're interested or having any questions, feel free to reach out! 😀

**Comment by apophis133** [comment]
Hello Sir,

I’d happily contribute to the cybersecurity community by adding my extractors to Assemblyline!
It's great to see collaborative efforts like this.
However, I’d like to ensure that all the YARA rules and extractors I provide are credited to me. Let me know how we can proceed with that, and feel free to reach out if you have any questions!

**Comment by cccs-rs** [comment]
Fantastic! I appreciate you're willingness to collaborate on integration with this project.

I can assure you all appropriate accreditation will be provided by amending the README in the [ConfigExtractor](https://github.com/CybercentreCanada/assemblyline-service-configextractor) service repository to highlight your contributions. 😁

In terms of how we should proceed, let me give a bit of background about the service:

The underlying library that "collects" and runs the extractors is [configextractor-py](https://github.com/CybercentreCanada/configextractor-py) which is written to support multiple extractor frameworks in a common tool and outputs to a common standard called [MACO](https://github.com/CybercentreCanada/Maco) which undergoes data validation via Pydantic. The library has official support for MWCP and MACO extractors, still pending on malduck support 🤞🤞.

Since your extractors don't seem to follow any of the supported frameworks mentioned, I would suggest creating an entrypoint file that we can autodetect with the library, similar to what I've suggested for [integration of RKP](https://github.com/jeFF0Falltrades/rat_king_parser/issues/7#issuecomment-2329646991). This assumes that refactoring your extractors to follow a certain framework is out of the question because of how it's used for your own work.

If there's anything you'd like me to provide clarification on, feel free to let me know!

**Comment by apophis133** [comment]
That's great to hear! I'm on board with creating the entry-point file for autodetecting the extractors.
Please let me know how I can help you in the coming time
and send me a message by email so we can communicate privately.
